homeassistant: true
permit_join: false
mqtt:
  base_topic: z2m
  server: mqtt://localhost
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: /dev/ttyUSB0
advanced:
  output: attribute_and_json
devices: devices.yaml
groups: groups.yaml
frontend:
  port: 8090

